# This is a build configuration for travis-ci.org
language: c

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install fakechroot
    - sudo pip install cpp-coveralls

script:
    - make && make test
    - make testbuild && make test
    # We do both just in case 'testbuild' is somehow different.

after_success:
    - coveralls
